[package]
name = "realtime_spectrogram"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
crossbeam-channel = "0.5"
rustfft = "6.1"
ratatui = "0.26"
crossterm = "0.27"
anyhow = "1.0"
num-traits = "0.2"


[[bin]]
name = "list_devices"
path = "src/list_devices.rs"